name: RunPythonScript

on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4

      with:
        python-version: '3.11'

    - name: Run Python Script
      run: python python.py
